# Generated by Django 6.0.1 on 2026-05-07 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='default.png', upload_to='profile_pictures/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='skills_needed',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='skills_offered',
            field=models.TextField(blank=True),
        ),
    ]
