# Generated by Django 6.0.1 on 2026-05-16 13:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill',
            name='resource_file',
            field=models.FileField(blank=True, null=True, upload_to='skill_resources/'),
        ),
        migrations.AddField(
            model_name='skill',
            name='resource_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('coding', 'Coding'), ('design', 'Design'), ('editing', 'Editing'), ('teaching', 'Teaching')], max_length=50),
        ),
        migrations.AlterField(
            model_name='skill',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
