# Generated by Django 6.0.1 on 2026-05-16 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_skill_created_at_skill_resource_file_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='resource_link',
            new_name='demo_link',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='resource_file',
        ),
        migrations.AddField(
            model_name='skill',
            name='demo_file',
            field=models.FileField(blank=True, null=True, upload_to='demo_resources/'),
        ),
        migrations.AddField(
            model_name='skill',
            name='premium_file',
            field=models.FileField(blank=True, null=True, upload_to='premium_resources/'),
        ),
        migrations.AddField(
            model_name='skill',
            name='premium_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
