# Generated by Django 6.0.1 on 2026-05-16 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0003_rename_resource_link_skill_demo_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='demo_file',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='demo_link',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='premium_file',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='premium_link',
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('resource_type', models.CharField(choices=[('demo', 'Demo'), ('premium', 'Premium')], max_length=20)),
                ('link', models.URLField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='resources/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='skills.skill')),
            ],
        ),
    ]
